# Generated by Django 6.1.1 on 2026-09-23 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_cart_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product_url', models.URLField(blank=True, default='', max_length=1000)),
                ('extracted_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_prices', to='accounts.product')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
